### PR TITLE
Adding voting proceedures

### PR DESCRIPTION
**Pull request by aterrel**
Here are the current voting procedures. Please comment or suggest changes as needed.

### CODE REVIEW

**Review by labarba — APPROVED** [review]
Looks good.

**Review by xorJane — APPROVED** [review]
LGTM as well

**Comment by labarba** [comment]
One thing we need to clarify, though, is the process for notifying the board that a vote is open. 

We cannot rely on GitHub notifications—like, for example, for this very issue right here. It's just lucky that I paid attention to this notification. But it wastes people's time: you have to activate that neuron connection that picks out the vote among a dozen other notifications that flood our inbox daily, then follow the link, activate the neuron that finds changed files and follow that link, blah blah. This cannot be our method.

**Review by SylvainCorlay — APPROVED** [review]
Looks good to me.

**Comment by aterrel** [comment]
@labarba great point! (especially since I didn't see your comment here for four days =P)

I've added that an email needs to be sent out to directors@numfocus.org

**Pull request merged**
